/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <main.h>
#include "led.h"

void task1_handler(void);  // This is task 1.
void task2_handler(void);  // This is task 2.
void task3_handler(void);  // This is task 3.
void task4_handler(void);  // This is task 4.
void taskIdle_handler(void); // This is idle task.


void enable_processor_faults(void);
void init_sched_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void init_systick(uint32_t tick_hz);
void switch_msp_to_psp();

// Global data space.
uint32_t current_task = 1;
uint32_t g_tick_count = 0;

typedef struct TCB
{
	uint32_t psp_value;
	uint32_t block_count;
	uint32_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();

	init_sched_stack(SCHED_STACK_START);

	init_tasks_stack();

	// led_init();

	init_systick(TICK_HZ);

	switch_msp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void enable_processor_faults(void)
{
	// enable fault into "System Handler Control and State Register".
	uint32_t *pSHCSR = (uint32_t *) 0xE000ED24;

	*pSHCSR |= (1 << 16); // Enable MemManage Fault Status.
	*pSHCSR |= (1 << 17); // Enable Bus Fault Status.
	*pSHCSR |= (1 << 18); // Enable UsageFault status.
}

void __attribute__((naked)) init_sched_stack(uint32_t sched_top_of_stack)
{
   __asm volatile("MSR MSP, %0": : "r" (sched_top_of_stack): );
   __asm volatile("BX LR");
}



void init_tasks_stack(void)
{
	user_tasks[0].current_state = TASK_STATE_READY;
	user_tasks[1].current_state = TASK_STATE_READY;
	user_tasks[2].current_state = TASK_STATE_READY;
	user_tasks[3].current_state = TASK_STATE_READY;
	user_tasks[4].current_state = TASK_STATE_READY;

	user_tasks[0].psp_value = TI_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = taskIdle_handler;
	user_tasks[1].task_handler = task2_handler;
	user_tasks[2].task_handler = task3_handler;
	user_tasks[3].task_handler = task4_handler;
	user_tasks[4].task_handler = task4_handler;




	uint32_t *pPSP;

    for(int i = 0; i < MAX_TASKS; i++)
    {
    	pPSP = (uint32_t *)user_tasks[i].psp_value;

    	// xPSR
    	pPSP--;
    	*pPSP = DUMMY_XPSR;    // Indicate thumb state.

    	// PC
    	pPSP--;
    	*pPSP = (uint32_t)user_tasks[i].task_handler; // Handle function of task.

    	// LR
    	pPSP--;
    	*pPSP = 0xFFFFFFFD; // EXC_RETURN -  Return in thread mode and use PSP

    	// Set register dummy value to 0, (R0-R3, R12 and R4-411)
    	for(int j = 0; j < 13; j++)
    	{
    		pPSP--;
    		*pPSP = 0;
    	}

    	// Store current PSP.
    	user_tasks[i].psp_value = (uint32_t)pPSP;
    }
}

void init_systick(uint32_t tick_hz)
{
	// Address of "S Reload Value Register"
	uint32_t *pSRVR = (uint32_t *)0xE000E014;

	// Address of "S Counter S Register"
	uint32_t *pSCSR = (uint32_t *)0xE000E010;

	// Calculate counter value.
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

	// Clear the value of reload value register.
	*pSRVR = 0;

	// Set reload value.
	*pSRVR |= count_value;

	// Settings to enable systick exception and set clock source.
	*pSCSR |= (1 << 1); // Enable systick exception.
	*pSCSR |= (1 << 2); // Set clock source to processor.

	// Enable systick.
	*pSCSR |= (1 << 0); // Enables the counter.
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

void __attribute__((naked)) switch_msp_to_psp(void)
{

    __asm volatile("PUSH {LR}");         // push LR so that later, we can use LR to return.
    __asm volatile("BL get_psp_value");  // get psp of current task.
    // Restore LR.
    __asm volatile("POP {LR}");

    // 1. Initialize PSP
    __asm volatile("MSR PSP, R0");

    // 2. switch SP from MSP to PSP using CONTROL register.
    __asm volatile("MOV R0, #0x02");
    __asm volatile("MSR CONTROL, R0");

    // 3. Go back to caller.
    __asm volatile("BX LR");
}

void save_psp_value(uint32_t psp_value)
{
	user_tasks[current_task].psp_value = psp_value;
}

void update_next_task(void)
{
    int state = TASK_STATE_BLOCKED;

    for(int i = 0; i < MAX_TASKS; i++)
    {
    	current_task++;
    	current_task = current_task % MAX_TASKS;

    	if((current_task != 0)
    			&& (user_tasks[current_task].current_state == TASK_STATE_READY))
    	{
    		// found task ready to schedule.
    		state = user_tasks[current_task].current_state;
    		break;
    	}
    }

    if(state != TASK_STATE_READY)
    {
    	current_task = 0;
    }
}

void schedule(void)
{
	uint32_t *pICSR = (uint32_t *)0xE000ED04;


	// PendSV exception to actually schedule next task and context switch accordingly.
	*pICSR |= (1<<28);
}

void task_delay(uint32_t tick_count)
{
	// This method can be called by any of tasks.
	// disable interrupt and enable after accessing global variables.
	INTERRUPED_DISABLE();

	if(current_task)
	{
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_STATE_BLOCKED;

		schedule();
	}

	INTERRUPED_ENABLE();

}


__attribute((naked)) void PendSV_Handler(void)
{
    // Save LR
    __asm volatile("PUSH {LR}");

    /**
     * Save the context of current task.
     * 1. Get the PSP of current task.
     * 2. Save SF2(R4-R11) and decrement PSP
     * 3. Save current PSP
     */

    // 1. Get the PSP of current task.
    __asm volatile("MRS R0, PSP");

    // 2. Save SF2(R4-R11) and decrement PSP.
    // __asm volatile("PUSH {R4,R11}"); // Cant 't use PUSH as it will write SF2 on MSP.
    __asm volatile("STMDB R0!, {R4-R11}");

    // 3. Save the current PSP.
    __asm volatile("BL save_psp_value");

    // Decide on next task based on scheduling algo, e.g. Round Robin.
    __asm volatile("BL update_next_task");


    /**
     * Retrieve context of next task.
     * 1. Get the PSP of the next task.
     * 2. POP SF2(R4-R11) and increment PSP.
     * 3. set PSP to current PSP.
     */

    // 1. Get the PSP of the next task.
    __asm volatile("BL get_psp_value");

    // 2. POP SF2(R4-R11) and increment PSP.
    __asm volatile("LDMIA R0!, {R4-R11}");

    // 3. Set SP = PSP
    __asm volatile("MSR PSP, R0");

    // POP LR and branch.
    __asm volatile("POP {LR}");
    __asm volatile("BX LR");
}

void update_global_tick_count()
{
	g_tick_count++;
}

void unblock_tasks()
{
	for(int i = 1; i < MAX_TASKS; i++)
	{
        if(user_tasks[i].current_state != TASK_STATE_READY)
        {
        	if(user_tasks[i].block_count == g_tick_count)
        	{
                user_tasks[i].current_state = TASK_STATE_READY;
        	}
        }
	}
}

void SysTick_Handler(void)
{
	uint32_t *pICSR = (uint32_t *)0xE000ED04;

    // 1. update global tick count.
	update_global_tick_count();

	//2. Unblock tasks
	unblock_tasks();

	// 3. PendSV exception to actually switch context.
	*pICSR |= (1<<28);


}

void taskIdle_handler(void)
{
	while(1);
}

void task1_handler(void)
{
    while(1)
    {
    	// led_on(LED_GREEN);
    	task_delay(1000);
    	// led_off(LED_GREEN);
    	task_delay(1000);
    }
}
void task2_handler(void)
{
    while(1)
    {
    	// led_on(LED_RED);
    	task_delay(500);
    	// led_off(LED_RED);
    	task_delay(500);
    }
}
void task3_handler(void)
{
    while(1)
    {
    	// led_on(LED_GREEN);
    	task_delay(250);
    	// led_off(LED_GREEN);
    	task_delay(250);
    }
}
void task4_handler(void)
{
    while(1)
    {
    	//led_on(LED_RED);
    	task_delay(125);
    	//led_off(LED_RED);
    	task_delay(125);
    }
}

void HardFault_Handler(void)
{
    printf("Exception: HardFault.\n");
    while(1);
}
void MemManage_Handler(void)
{
    printf("Exception: MemManage Fault.\n");
    while(1);
}
void BusFault_Handler(void)
{
    printf("Exception: BusFault.\n");
    while(1);
}
void UsageFault_Handler(void)
{
    printf("Exception: UsageFault.\n");
    while(1);
}
