/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void task1_handler(void);  // This is task 1.
void task2_handler(void);  // This is task 2.
void task3_handler(void);  // This is task 3.
void task4_handler(void);  // This is task 4.


void enable_processor_faults(void);
void init_sched_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void init_systick(uint32_t tick_hz);
void switch_msp_to_psp();

// Global data space.
uint32_t psp_of_tasks[MAX_TASKS] = {};
uint32_t task_handlers[MAX_TASKS] = {(uint32_t)task1_handler, (uint32_t)task2_handler, (uint32_t)task3_handler, (uint32_t)task4_handler};


int main(void)
{
	enable_processor_faults();

	init_sched_stack(SCHED_START_START);

	init_tasks_stack();

	init_systick(TICK_HZ);

	switch_msp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void enable_processor_faults(void)
{
	// enable fault into "System Handler Control and State Register".
	uint32_t *pSHCSR = (uint32_t *) 0xE000ED24;

	*pSHCSR |= (1 << 16); // Enable MemManage Fault Status.
	*pSHCSR |= (1 << 17); // Enable Bus Fault Status.
	*pSHCSR |= (1 << 18); // Enable UsageFault status.
}

void __attribute__((naked)) init_shed_stack(uint32_t sched_top_of_stack)
{
   __asm volatile("MSR MSP, %0": : "r" (sched_top_of_stack): );
   __asm volatile("BX LR");
}

void init_tasks_stack(void)
{
	uint32_t *pPSP;

    for(int i = 0; i < MAX_TASKS; i++)
    {
    	pPSP = (unit32_t *) psp_of_tasks[i];

    	// xPSR
    	*pPSP--;
    	*pPSP = DUMMY_XPSR;    // Indicate thumb state.

    	// PC
    	*pPSP--;
    	*pPSP = task_handlers[i]; // Handle function of task.

    	// LR
    	*pPSP--;
    	*pPSP = 0xFFFFFFFD; // EXC_RETURN -  Return in thread mode and use PSP

    	// Set register dummy value to 0, (R0-R3, R12 and R4-411)
    	for(int j = 0; j < 13; j++)
    	{
    		pPSP--;
    		*pPSP = 0;
    	}

    	// Store current PSP.
    	psp_of_tasks[i] = (uint32_t)pPSP;
    }
}

void init_systick(uint32_t tick_hz)
{
	// Address of "S Reload Value Register"
	uint32_t *pSRVR = (uint32_t *)0xE000E014;

	// Address of "S Counter S Register"
	uint32_t *pSCSR = (uint32_t *)0xE000E010;

	// Calculate counter value.
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

	// Clear the value of reload value register.
	*pSRVR = 0;

	// Set reload value.
	*pSRVR |= count_value;

	// Settings to enable systick exception and set clock source.
	*pSCSR |= (1 << 1); // Enable systick exception.
	*pSCSR |= (1 << 2); // Set clock source to processor.

	// Enable systick.
	*pSCSR |= (1 << 0); // Enables the counter.
}

void __attribute__((naked)) switch_msp_to_psp(void)
{

}

void SysTick_Handler(void)
{

}

void task1_handler(void)
{

}
void task2_handler(void)
{

}
void task3_handler(void)
{

}
void task4_handler(void)
{

}

void HardFault_Handler(void)
{

}
void MemManage_Handler(void)
{

}
void BusFault_Handler(void)
{

}
void UsageFault_Handler(void)
{

}
